language: python
python:
  - "3.6"
before_install:
  - sudo apt-get install python-lxml
install: 
  - pip install coveralls
  - pip install tox
script: tox
env:
  - TOXENV=py36sqlite
  - TOXENV=py36pg
  - TOXENV=flake8
  - TOXENV=packaging
  - TOXENV=docs
after_success:
  coveralls
